### ISSUE TITLE
README.rst does not format correctly on PyPi

### ISSUE THREAD

**Issue by shortdudey123** [leosartaj/autosign#1]
On PyPi the readme shows up as pure text and not formatted.  Presumably is it due to the use of :: for code blocks.

http://stackoverflow.com/questions/17401132/restructuredtext-readme-rst-not-parsing-on-pypi

**Comment by leosartaj** [comment]
i tried changing the syntax, and using .. code-block::, but still no luck. Any other suggestion?

**Comment by leosartaj** [comment]
I think i made a syntax mistake. Let me update.

**Comment by shortdudey123** [comment]
Not sure.  You can also use the testing server as well instead of testing on the main site.

https://wiki.python.org/moin/TestPyPI

**Comment by leosartaj** [comment]
Syntax related problem have been fixed. Closing issue.
